version: "2"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d:ro
    - ./nginx/html:/usr/share/nginx/html:ro
    - ./nginx/log:/var/log/nginx/
    ports:
    - "8001:80"
    depends_on:
    - jt-ams
    - jt-wrs
    - jt-jess

  jt-ams:
    image: quay.io/junjun_zhang/jt-ams:0.2.0a7
    environment:
    - ETCD_HOST=etcd
    command:
    - python3
    - /srv/jt-ams/app.py
    ports:
    - 12012:12012
    depends_on:
    - etcd

  jt-wrs:
    image: quay.io/junjun_zhang/jt-wrs:0.2.0a7
    environment:
    - ETCD_HOST=etcd
    - AMS_HOST=jt-ams
    command:
    - python3
    - /srv/jt-wrs/app.py
    ports:
    - 12015:12015
    depends_on:
    - etcd

  jt-jess:
    image: quay.io/junjun_zhang/jt-jess:0.2.0a9
    environment:
    - ETCD_HOST=etcd
    - AMS_HOST=jt-ams
    - WRS_HOST=jt-wrs
    command:
    - python3
    - /srv/jt-jess/app.py
    ports:
    - 12018:12018
    depends_on:
    - etcd

  etcd:
    image: quay.io/coreos/etcd:v3.3
    environment:
    - ETCD_DATA_DIR=/etcd-data
    command:
    - etcd
    - --name=etcd0
    - --advertise-client-urls=http://etcd:2379
    - --listen-client-urls=http://0.0.0.0:2379
    - --initial-advertise-peer-urls=http://etcd:2380
    - --initial-cluster-state=new
    - --quota-backend-bytes=4294967296  # default 4GB
    ports:
    - 2379:2379
    volumes:
    - ./etcd-data:/etcd-data
